
//video lists
export const GET_VIDEO_LIST_REQUEST = 'GET_VIDEO_LIST_REQUEST';
export const GET_VIDEO_LIST_SUCCESS = 'GET_VIDEO_LIST_SUCCESS';
export const GET_VIDEO_LIST_FAILURE = 'GET_VIDEO_LIST_FAILURE';

//stripe lists
export const GET_STRIPE_LIST_REQUEST = 'GET_STRIPE_LIST_REQUEST';
export const GET_STRIPE_LIST_SUCCESS = 'GET_STRIPE_LIST_SUCCESS';
export const GET_STRIPE_LIST_FAILURE = 'GET_STRIPE_LIST_FAILURE';